if (typeof requireAuth === "function") requireAuth();

function showLoading() {
    const el = document.getElementById('loading');
    if (el) el.style.display = 'flex';
}
function hideLoading() {
    const el = document.getElementById('loading');
    if (el) el.style.display = 'none';
}

function downloadBlob(content, type, filename) {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}

window.generateExpensePDF = async () => {
    showLoading();
    try {
        const expenses = await apiRequest('/farmer/expenses') || [];
        const crops = await apiRequest('/farmer/crops') || [];
        // BUG FIX: e.amount could be null/undefined, causing NaN in totals;
        // now guarded with Number(... || 0).
        const totalExpenses = expenses.reduce((sum, e) => sum + Number(e.amount || 0), 0);

        let html = `<html><head><title>Expense Report</title></head><body>
            <h1>FarmProfit - Expense Report</h1><h3>Date: ${new Date().toLocaleDateString()}</h3>
            <h3>Total Crops: ${crops.length}</h3><h3>Total Expenses: ₹${totalExpenses.toLocaleString()}</h3>
            <table border="1" cellpadding="5"><tr><th>Type</th><th>Amount</th><th>Crop</th><th>Description</th><th>Date</th></tr>
            ${expenses.map(e => `<tr><td>${e.expenseType || '-'}</td><td>₹${Number(e.amount || 0).toLocaleString()}</td><td>${e.crop ? e.crop.cropName : 'General'}</td><td>${e.description || '-'}</td><td>${e.expenseDate || 'N/A'}</td></tr>`).join('')}
            </table><p>Generated by FarmProfit System</p></body></html>`;

        downloadBlob(html, 'text/html', `expense_report_${new Date().toISOString().split('T')[0]}.html`);
        alert('Report generated successfully!');
    } catch (error) {
        console.error(error);
        alert('Error generating report: ' + error.message);
    } finally { hideLoading(); }
};

window.generateProfitExcel = async () => {
    showLoading();
    try {
        const data = await apiRequest('/farmer/profit/calculate');
        let csv = "Crop Name,Revenue (Rs),Expense (Rs),Profit (Rs),Profit Margin (%)\n";
        (data.cropProfits || []).forEach(p => {
            // BUG FIX: profitMargin/netProfit could be undefined for edge
            // cases (e.g. zero revenue), which crashed .toFixed().
            const margin = typeof p.profitMargin === 'number' ? p.profitMargin.toFixed(2) : '0.00';
            csv += `"${p.cropName}",${p.totalRevenue || 0},${p.totalExpense || 0},${p.netProfit || 0},${margin}\n`;
        });
        csv += `\n"TOTAL",${data.totalRevenue || 0},${data.totalExpenses || 0},${data.totalProfit || 0},${typeof data.totalProfitMargin === 'number' ? data.totalProfitMargin.toFixed(2) : '0.00'}\n`;
        if (data.generalExpenses) {
            csv += `"(includes General/unassigned expenses)",,${data.generalExpenses},,\n`;
        }

        downloadBlob(csv, 'text/csv', `profit_report_${new Date().toISOString().split('T')[0]}.csv`);
        alert('Profit report generated!');
    } catch (error) {
        console.error(error);
        alert('Error generating report: ' + error.message);
    } finally { hideLoading(); }
};

window.generateCropReport = async () => {
    showLoading();
    try {
        const crops = await apiRequest('/farmer/crops') || [];
        let html = `<html><head><title>Crop Report</title></head><body>
            <h1>Crop Performance Report</h1><h3>Generated: ${new Date().toLocaleString()}</h3>
            <table border="1" cellpadding="5"><tr><th>Crop Name</th><th>Area (Acres)</th><th>Season</th><th>Expected Yield</th><th>Market Price</th></tr>
            ${crops.map(c => `<tr><td>${c.cropName}</td><td>${c.area ?? '-'}</td><td>${c.season || '-'}</td><td>${c.expectedYield ?? '-'}</td><td>${c.marketPrice ?? '-'}</td></tr>`).join('')}
            </table></body></html>`;
        downloadBlob(html, 'text/html', `crop_report_${new Date().toISOString().split('T')[0]}.html`);
        alert('Crop report generated!');
    } catch (error) {
        console.error(error);
        alert('Error generating report: ' + error.message);
    } finally { hideLoading(); }
};

// EXTRA FEATURE: one combined report - crops, expenses and profit in a single document
window.generateFullReport = async () => {
    showLoading();
    try {
        const [crops, expenses, profitData] = await Promise.all([
            apiRequest('/farmer/crops'),
            apiRequest('/farmer/expenses'),
            apiRequest('/farmer/profit/calculate')
        ]);

        const totalExpenses = (expenses || []).reduce((sum, e) => sum + Number(e.amount || 0), 0);

        const html = `<html><head><title>Full Farm Report</title>
        <style>body{font-family:Arial,sans-serif;padding:20px}table{width:100%;border-collapse:collapse;margin-bottom:20px}
        th,td{border:1px solid #ccc;padding:6px 10px;text-align:left}th{background:#2ecc71;color:#fff}
        h1{color:#1e3c2c}h2{border-bottom:2px solid #2ecc71;padding-bottom:4px}</style></head><body>
        <h1>FarmProfit - Full Farm Report</h1>
        <p>Generated: ${new Date().toLocaleString()}</p>

        <h2>Summary</h2>
        <table>
            <tr><th>Total Crops</th><td>${(crops || []).length}</td></tr>
            <tr><th>Total Expenses</th><td>₹${totalExpenses.toLocaleString()}</td></tr>
            <tr><th>Total Revenue</th><td>₹${(profitData.totalRevenue || 0).toLocaleString()}</td></tr>
            <tr><th>Net Profit</th><td>₹${(profitData.totalProfit || 0).toLocaleString()}</td></tr>
            <tr><th>Profit Margin</th><td>${typeof profitData.totalProfitMargin === 'number' ? profitData.totalProfitMargin.toFixed(2) : '0.00'}%</td></tr>
        </table>

        <h2>Crops</h2>
        <table><tr><th>Crop</th><th>Area (Acres)</th><th>Season</th><th>Expected Yield</th><th>Market Price</th></tr>
        ${(crops || []).map(c => `<tr><td>${c.cropName}</td><td>${c.area ?? '-'}</td><td>${c.season || '-'}</td><td>${c.expectedYield ?? '-'}</td><td>${c.marketPrice ?? '-'}</td></tr>`).join('')}
        </table>

        <h2>Expenses</h2>
        <table><tr><th>Type</th><th>Amount</th><th>Crop</th><th>Description</th><th>Date</th></tr>
        ${(expenses || []).map(e => `<tr><td>${e.expenseType || '-'}</td><td>₹${Number(e.amount || 0).toLocaleString()}</td><td>${e.crop ? e.crop.cropName : 'General'}</td><td>${e.description || '-'}</td><td>${e.expenseDate || 'N/A'}</td></tr>`).join('')}
        </table>

        <h2>Profit by Crop</h2>
        <table><tr><th>Crop</th><th>Revenue</th><th>Expense</th><th>Net Profit</th><th>Margin</th><th>Recommendation</th></tr>
        ${(profitData.cropProfits || []).map(p => `<tr><td>${p.cropName}</td><td>₹${(p.totalRevenue || 0).toLocaleString()}</td><td>₹${(p.totalExpense || 0).toLocaleString()}</td><td>₹${(p.netProfit || 0).toLocaleString()}</td><td>${typeof p.profitMargin === 'number' ? p.profitMargin.toFixed(2) : '0.00'}%</td><td>${p.recommendation || '-'}</td></tr>`).join('')}
        </table>

        <p>Generated by FarmProfit System</p>
        </body></html>`;

        downloadBlob(html, 'text/html', `full_farm_report_${new Date().toISOString().split('T')[0]}.html`);
        alert('Full farm report generated!');
    } catch (error) {
        console.error(error);
        alert('Error generating full report: ' + error.message);
    } finally { hideLoading(); }
};
